### ISSUE TITLE
OAuth2Strategy requires a clientID option

### ISSUE THREAD

**Issue by ghost** [guymargalit/thundr#3]
Getting this error when running yarn start in the server
  
  if (!options.clientID) { throw new TypeError('OAuth2Strategy requires a clientID option'); }
                           ^

TypeError: OAuth2Strategy requires a clientID option
    at Strategy.OAuth2Strategy (/home/linux/Desktop/thundr-master/server/node_modules/passport-oauth2/lib/strategy.js:86:34)
    at new Strategy (/home/linux/Desktop/thundr-master/server/node_modules/passport-spotify/lib/passport-spotify/strategy.js:56:18)
    at Object.<anonymous> (/home/linux/Desktop/thundr-master/server/src/index.js:18:18)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47
[nodemon] app crashed - waiting for file changes before starting...

**Comment by guymargalit** [comment]
You'll need to get a Client ID and Client Secret from Spotify and put it in your .env (https://developer.spotify.com/dashboard/)

**Comment by ghost** [comment]
Whats .env? I dont know what file this is?
